export const LANGUAGES: { flag: string; lang: string }[] = [
  { flag: "🇩🇪", lang: "Deutsch" },
  { flag: "🇬🇧", lang: "English" },
  { flag: "🇦🇷", lang: "Español" },
  { flag: "🇮🇹", lang: "Italiano" },
  { flag: "🇧🇷", lang: "Português" },
  { flag: "🇯🇵", lang: "日本語" },
  { flag: "🇨🇳", lang: "中文" },
  { flag: "🌐", lang: "Esperanto" },
  { flag: "🇫🇷", lang: "Français" },
  { flag: "🇮🇱", lang: "עברית" },
  { flag: "🇻🇦", lang: "Latina" },
  { flag: "🇳🇱", lang: "Nederlands" },
  { flag: "🇸🇪", lang: "Svenska" },
  { flag: "🇺🇦", lang: "Українська" },
  { flag: "🕴️", lang: "LinkedIn" },
  { flag: "💾", lang: "Leet" },
  { flag: "⚪", lang: "Minimal" },
  { flag: "✨", lang: "Star Wars" },
  { flag: "🧑‍🎤", lang: "Cyberpunk" },
  { flag: "🦿", lang: "AISLOP" },
  { flag: "🚀", lang: "NASA" },
  { flag: "🧬", lang: "Gen Alpha" },
  { flag: "🤠", lang: "Cowboy" },
];
