/**
 * One-shot seed script: populates SQLite with all projects from the old projectsData.
 * Run once after first install: npm run seed
 * After running, you can delete this file and utils/projectsData.js.
 */

import Database from 'better-sqlite3';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { mkdirSync } from 'fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dbDir = join(__dirname, '../../db');
const dbPath = join(dbDir, 'fabio.db');

mkdirSync(dbDir, { recursive: true });

const db = new Database(dbPath);
db.pragma('journal_mode = WAL');

db.exec(`
  CREATE TABLE IF NOT EXISTS projects (
    id            TEXT PRIMARY KEY,
    title         TEXT NOT NULL,
    desc_de       TEXT DEFAULT '',
    desc_en       TEXT DEFAULT '',
    desc_es       TEXT DEFAULT '',
    desc_it       TEXT DEFAULT '',
    desc_ja       TEXT DEFAULT '',
    desc_pt       TEXT DEFAULT '',
    categories    TEXT NOT NULL DEFAULT '[]',
    published     INTEGER NOT NULL DEFAULT 0,
    finished      INTEGER NOT NULL DEFAULT 0,
    online        INTEGER NOT NULL DEFAULT 0,
    image         TEXT DEFAULT '',
    url           TEXT DEFAULT '',
    languages     TEXT NOT NULL DEFAULT '[]'
  );

  CREATE TABLE IF NOT EXISTS contact_submissions (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    name          TEXT NOT NULL,
    email         TEXT NOT NULL,
    message       TEXT NOT NULL,
    ip_hash       TEXT,
    submitted_at  DATETIME DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE IF NOT EXISTS rate_limits (
    ip_hash       TEXT PRIMARY KEY,
    count         INTEGER NOT NULL DEFAULT 1,
    window_start  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  );
`);

const projects = [
  {
    id: "7",
    title: "NeverAtHome",
    desc_de: "Entwicklung und Konzeption, Webseite, Plattformprojekt, Newsletter, Sysadmintätigkeiten sowie kommender Multi-Tenant Option für Mitglieder:innen",
    desc_en: "Development and Conception, Website, Platform Project, Newsletter, Sysadmin Tasks and upcoming Multi-Tenant Option for Members",
    desc_es: "Proyecto de Plataforma, Sitio Web, Newsletter, Actividades de Sysadmin y próxima opción Multi-Tenant para miembros",
    desc_it: "Progettazione e Concezione, Sito Web, Progetto Piattaforma, Newsletter, Attività Sysadmin e prossima opzione Multi-Tenant per i membri",
    desc_ja: "",
    desc_pt: "",
    categories: JSON.stringify(["SvelteKit","SCSS","Lucia","Postgres","Go","Selfhosted","GCP","Astro","NodeJS","Typescript"]),
    published: 1, finished: 0, online: 1,
    image: "/RZ_NeverAtHome_Sharebild_compressed.png",
    url: "https://never-at-home.at",
    languages: JSON.stringify([{lang:"English",flag:"🇺🇸"},{lang:"Deutsch",flag:"🇩🇪"}]),
  },
  {
    id: "3",
    title: "Centropa Stories - Podcast",
    desc_de: "Entwicklung und Konzeption",
    desc_en: "Development and Conception",
    desc_es: "",
    desc_it: "Sviluppo e Concezione",
    desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Next.js","TailwindCSS","Headless UI","Vercel","Drupal","Splitbee","Github"]),
    published: 0, finished: 1, online: 0,
    image: "/ukmko008(1).jpg",
    url: "https://podcast.centropa.org",
    languages: JSON.stringify([{lang:"Deutsch",flag:"🇩🇪"},{lang:"English",flag:"🇺🇸"},{lang:"Ukrainian",flag:"🇺🇦"}]),
  },
  {
    id: "4",
    title: "Ukrainian Stories - Centropa",
    desc_de: "Entwicklung und Konzeption",
    desc_en: "Development and Conception",
    desc_es: "", desc_it: "Sviluppo e Concezione", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Next.js","TailwindCSS","Headless UI","Vercel","Drupal","Splitbee","Github"]),
    published: 0, finished: 1, online: 0,
    image: "",
    url: "https://ukrainianstories.centropa.org",
    languages: JSON.stringify([{lang:"Deutsch",flag:"🇩🇪"},{lang:"English",flag:"🇺🇸"},{lang:"Ukrainian",flag:"🇺🇦"}]),
  },
  {
    id: "5",
    title: "ProjectDecider",
    desc_de: "Design, Entwicklung und Konzeption, Entscheidungshelfer woran heute gearbeitet wird",
    desc_en: "Development and Conception",
    desc_es: "", desc_it: "Sviluppo e Concezione", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Angular","CSS","MongoDB","Vercel"]),
    published: 1, finished: 1, online: 0,
    image: "",
    url: "https://projectdecider.vercel.app",
    languages: JSON.stringify([{lang:"English",flag:"🇺🇸"}]),
  },
  {
    id: "6",
    title: "Dorcol - Centropa",
    desc_de: "Entwicklung und Konzeption",
    desc_en: "Development and Conception",
    desc_es: "", desc_it: "Sviluppo e Concezione", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Next.js","TailwindCSS","HeadlessUI","Github","Vercel","Splitbee"]),
    published: 1, finished: 1, online: 0,
    image: "",
    url: "https://dorcol.centropa.app",
    languages: JSON.stringify([{lang:"English",flag:"🇺🇸"},{lang:"Serbian",flag:"🇷🇸"}]),
  },
  {
    id: "1",
    title: "Fabio.sh",
    desc_de: "Design, Entwicklung und Konzeption",
    desc_en: "Design, development and concept",
    desc_es: "", desc_it: "Progettazione, Sviluppo e Concezione", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Astro","TailwindCSS","SQLite","Node.js"]),
    published: 1, finished: 0, online: 1,
    image: "/meta_pic.png",
    url: "https://fabio.sh",
    languages: JSON.stringify([{lang:"Deutsch",flag:"🇩🇪"},{lang:"English",flag:"🇺🇸"},{lang:"Español",flag:"🇦🇷"},{lang:"Italiano",flag:"🇮🇹"},{lang:"Bras. Port.",flag:"🇧🇷"},{lang:"日本の",flag:"🇯🇵"}]),
  },
  {
    id: "2",
    title: "Radio International",
    desc_de: "Design, Entwicklung und Konzeption",
    desc_en: "Design, development and concept",
    desc_es: "", desc_it: "Progettazione, Sviluppo e Concezione", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Next.js","TailwindCSS","REST","GraphQL","Directus","Vercel Analytics","Selfhosted"]),
    published: 1, finished: 0, online: 1,
    image: "/ri_meta_pic.png",
    url: "https://radiointernational.org",
    languages: JSON.stringify([{lang:"Deutsch",flag:"🇩🇪"}]),
  },
  {
    id: "8",
    title: "ProjektDB",
    desc_de: "Design, Entwicklung und Konzeption, CMS & CRM für Grafikdesigner:innen mit Klienten und Rechnungsübersichten, etc...",
    desc_en: "Design, Development and Conception",
    desc_es: "", desc_it: "Progettazione, Sviluppo e Concezione", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Next.js","Typescript","trcp","TailwindCSS","HeadlessUI","NextAuth","Supabase","Vercel","Vercel Analytics"]),
    published: 0, finished: 0, online: 0,
    image: "", url: "",
    languages: JSON.stringify([{lang:"English",flag:"🇺🇸"},{lang:"Deutsch",flag:"🇩🇪"}]),
  },
  {
    id: "9",
    title: "ThreeJS Project",
    desc_de: "Design, Entwicklung und Konzeption",
    desc_en: "Design, Development and Conception",
    desc_es: "", desc_it: "Progettazione, Sviluppo e Concezione", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Next.js","Three.js"]),
    published: 0, finished: 0, online: 0,
    image: "", url: "",
    languages: JSON.stringify([{lang:"English",flag:"🇺🇸"},{lang:"Deutsch",flag:"🇩🇪"}]),
  },
  {
    id: "10",
    title: "dieDigitale Agency",
    desc_de: "Design, Entwicklung und Konzeption",
    desc_en: "Design, Development and Conception",
    desc_es: "", desc_it: "Progettazione, Sviluppo e Concezione", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Next.js","Three.js","TailwindCSS","NextAuth","Selfhosted","Vercel"]),
    published: 0, finished: 0, online: 0,
    image: "", url: "",
    languages: JSON.stringify([{lang:"English",flag:"🇺🇸"},{lang:"Deutsch",flag:"🇩🇪"}]),
  },
  {
    id: "11",
    title: "Therapie - Nina Luciak",
    desc_de: "Design, Entwicklung, Support und Konzeption",
    desc_en: "Design, Development, Support and Conception",
    desc_es: "", desc_it: "Progettazione, Sviluppo, Supporto e Concezione", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Gatsby.js","TailwindCSS","Email.js","Vercel"]),
    published: 0, finished: 1, online: 0,
    image: "",
    url: "https://ninaluciak.at",
    languages: JSON.stringify([{lang:"English",flag:"🇺🇸"},{lang:"Deutsch",flag:"🇩🇪"}]),
  },
  {
    id: "12",
    title: "veramica - Pers. Website",
    desc_de: "Design, Entwicklung und Konzeption",
    desc_en: "Design, Development and Conception",
    desc_es: "", desc_it: "Progettazione, Sviluppo e Concezione", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Next.js","Three.js","TailwindCSS","DatoCMS"]),
    published: 0, finished: 0, online: 0,
    image: "",
    url: "https://veramica.at",
    languages: JSON.stringify([{lang:"English",flag:"🇺🇸"},{lang:"Deutsch",flag:"🇩🇪"}]),
  },
  {
    id: "13",
    title: "MarcusWagner",
    desc_de: "Design, Entwicklung, Support und Konzeption",
    desc_en: "Design, Development, Support and Conception",
    desc_es: "", desc_it: "Progettazione, Sviluppo, Supporto e Concezione", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Next.js","Headless Wordpress","Graphql","TailwindCSS"]),
    published: 1, finished: 1, online: 1,
    image: "",
    url: "https://marcuswagner.at",
    languages: JSON.stringify([{lang:"English",flag:"🇺🇸"},{lang:"Deutsch",flag:"🇩🇪"}]),
  },
  {
    id: "24a",
    title: "CHOYCE",
    desc_de: "WebScraping für CHOYCE",
    desc_en: "WebScraping for CHOYCE",
    desc_es: "", desc_it: "WebScraping per CHOYCE", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Python","Selenium","CSV"]),
    published: 1, finished: 1, online: 1,
    image: "",
    url: "https://choyce.tech/",
    languages: JSON.stringify([{lang:"Deutsch",flag:"🇩🇪"}]),
  },
  {
    id: "14",
    title: "Sarajevo30 - Centropa",
    desc_de: "Entwicklung, Support, nur für Desktop Nutzung",
    desc_en: "Development, Support, only for desktop use",
    desc_es: "", desc_it: "Sviluppo e Supporto, solo per l'uso nel Desktop", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Next.js","TailwindCSS","Github"]),
    published: 0, finished: 1, online: 0,
    image: "",
    url: "https://sarajevo.centropa.org",
    languages: JSON.stringify([{lang:"Deutsch",flag:"🇩🇪"}]),
  },
  {
    id: "15",
    title: "Brandhofer-SFX",
    desc_de: "Entwicklung, Support, im Umbau - bald Headless DatoCMS",
    desc_en: "Development, Support, in heavy development, soon Headless DatoCMS",
    desc_es: "", desc_it: "Sviluppo, Supporto, in forte sviluppo, presto Headless DatoCMS", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Wordpress","Divi"]),
    published: 1, finished: 1, online: 1,
    image: "",
    url: "https://brandhofer-sfx.at/",
    languages: JSON.stringify([{lang:"Deutsch",flag:"🇩🇪"},{lang:"English",flag:"🇺🇸"}]),
  },
  {
    id: "16",
    title: "stuntworkshop.at",
    desc_de: "Entwicklung, Support",
    desc_en: "Development, Support",
    desc_es: "", desc_it: "Sviluppo, Supporto", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["NextJS","TailwindCSS","DatoCMS"]),
    published: 0, finished: 1, online: 1,
    image: "",
    url: "https://stuntworkshop.at/",
    languages: JSON.stringify([{lang:"Deutsch",flag:"🇩🇪"}]),
  },
  {
    id: "20",
    title: "Centropa - Main Site",
    desc_de: "Support", desc_en: "Support", desc_es: "", desc_it: "Supporto", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Drupal","TailwindCSS"]),
    published: 1, finished: 1, online: 1,
    image: "",
    url: "https://centropa.org/",
    languages: JSON.stringify([{lang:"English",flag:"🇺🇸"}]),
  },
  {
    id: "21",
    title: "UNODC - Conference Site",
    desc_de: "Support", desc_en: "Support", desc_es: "", desc_it: "Supporto", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Drupal 8"]),
    published: 1, finished: 1, online: 0,
    image: "", url: "",
    languages: JSON.stringify([{lang:"English",flag:"🇺🇸"}]),
  },
  {
    id: "17",
    title: "send.centropa",
    desc_de: "Design, Entwicklung, Support, Service zum Verteilen von Audiodateien",
    desc_en: "Design, Development, Support, service to share audio files",
    desc_es: "", desc_it: "Progettazione, Sviluppo, Supporto, servizio di condivisione di file audio", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Next.js","TailwindCSS"]),
    published: 1, finished: 1, online: 0,
    image: "",
    url: "https://send.centropa.org/",
    languages: JSON.stringify([{lang:"English",flag:"🇺🇸"}]),
  },
  {
    id: "22",
    title: "Centropa Bridge",
    desc_de: "Design, Entwicklung, Support, Service für Feedback, kleine 'E-Learning' Plattform zur Verbesserung der Zusammenarbeit und des Supports des international verteilten Teams",
    desc_en: "Design, Development, Support, service for feedback, small 'E-Learning' platform to enhance collaboration and support for the internationally divided team",
    desc_es: "", desc_it: "Progettazione, sviluppo, assistenza, servizio di feedback, piccola piattaforma di 'E-Learning' per migliorare la collaborazione e il supporto al team diviso a livello internazionale.", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Next.js","TailwindCSS","Supabase","Supabase Auth"]),
    published: 1, finished: 1, online: 0,
    image: "",
    url: "https://brigde.centropa.org/",
    languages: JSON.stringify([{lang:"English",flag:"🇺🇸"}]),
  },
  {
    id: "18",
    title: "Siegelgasse",
    desc_de: "Design, Entwicklung, Support, Mein Lebenslauf (Stand: 2019) Online nur mit Authentifizierung zu sehen --> Privatspäre ;)",
    desc_en: "Design, Development, Support, My CV (2019) online only accessible through authentification --> Privacy ;)",
    desc_es: "", desc_it: "Design, Sviluppo, Assistenza, Il mio CV (2019) online accessibile solo tramite autenticazione --> Privacy", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Angular","Typescript","CSS","Firebase"]),
    published: 1, finished: 1, online: 0,
    image: "",
    url: "https://siegelgasse.at/",
    languages: JSON.stringify([{lang:"English",flag:"🇺🇸"}]),
  },
  {
    id: "19",
    title: "Holocaust in Hungary",
    desc_de: "Design, Entwicklung, Support",
    desc_en: "Design, Development, Support",
    desc_es: "", desc_it: "Progettazione, Sviluppo, Supporto", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Wordpress","Divi"]),
    published: 1, finished: 1, online: 0,
    image: "",
    url: "https://holocaustinhungary.centropa.org/",
    languages: JSON.stringify([{lang:"English",flag:"🇺🇸"}]),
  },
  {
    id: "23",
    title: "ArtistenAllerArt",
    desc_de: "Entwicklung, Support",
    desc_en: "Development, Support",
    desc_es: "", desc_it: "Sviluppo, Supporto", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Wordpress","Divi"]),
    published: 1, finished: 1, online: 1,
    image: "",
    url: "https://artistenallerart.at/",
    languages: JSON.stringify([{lang:"Deutsch",flag:"🇩🇪"}]),
  },
  {
    id: "24b",
    title: "Gabriel Proedl",
    desc_de: "Design, Entwicklung und Konzeption",
    desc_en: "Design, development and concept",
    desc_es: "", desc_it: "Progettazione, Sviluppo e Concezione", desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Next.js","TailwindCSS","Vercel","Sanity.io"]),
    published: 0, finished: 0, online: 0,
    image: "/test.png",
    url: "https://gabrielproedl.com",
    languages: JSON.stringify([{lang:"Deutsch",flag:"🇩🇪"}]),
  },
  {
    id: "25",
    title: "Leando",
    desc_de: "Entwicklung",
    desc_en: "Development",
    desc_es: "Desarrollo",
    desc_it: "Sviluppo",
    desc_ja: "開発",
    desc_pt: "Desenvolvimento",
    categories: JSON.stringify(["Angular 17 & 19","Drupal 8 & 10","Decoupled","Typescript","SCSS"]),
    published: 1, finished: 0, online: 1,
    image: "",
    url: "https://leando.de",
    languages: JSON.stringify([{lang:"Deutsch",flag:"🇩🇪"}]),
  },
  {
    id: "26",
    title: "Tim Oppermann",
    desc_de: "Design, Entwicklung und Konzeption, E-Mail, Hosting",
    desc_en: "Design, development and concept, Email, Hosting",
    desc_es: "Diseño, desarrollo y concepto, Correo electrónico, Alojamiento",
    desc_it: "Progettazione, Sviluppo e Concezione, Email, Hosting",
    desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Next.js","TailwindCSS","Directus","Selfhosted","Vercel"]),
    published: 1, finished: 1, online: 1,
    image: "",
    url: "https://timoppermann.at",
    languages: JSON.stringify([{lang:"Deutsch",flag:"🇩🇪"},{lang:"English",flag:"🇬🇧"}]),
  },
  {
    id: "27",
    title: "Kollektiv Film",
    desc_de: "Design, Entwicklung und Konzeption, E-Mail, Hosting",
    desc_en: "Design, development and concept, Email, Hosting",
    desc_es: "Diseño, desarrollo y concepto, Correo electrónico, Alojamiento",
    desc_it: "Progettazione, Sviluppo e Concezione, Email, Hosting",
    desc_ja: "", desc_pt: "",
    categories: JSON.stringify(["Next.js","TailwindCSS","Directus","Selfhosted","Vercel"]),
    published: 1, finished: 1, online: 1,
    image: "",
    url: "https://www.kollektivfilm.at",
    languages: JSON.stringify([{lang:"Deutsch",flag:"🇩🇪"},{lang:"English",flag:"🇬🇧"}]),
  },
];

const insert = db.prepare(`
  INSERT OR REPLACE INTO projects
    (id, title, desc_de, desc_en, desc_es, desc_it, desc_ja, desc_pt,
     categories, published, finished, online, image, url, languages)
  VALUES
    (@id, @title, @desc_de, @desc_en, @desc_es, @desc_it, @desc_ja, @desc_pt,
     @categories, @published, @finished, @online, @image, @url, @languages)
`);

const insertMany = db.transaction((rows) => {
  for (const row of rows) insert.run(row);
});

insertMany(projects);

console.log(`✅ Seeded ${projects.length} projects into ${dbPath}`);
db.close();
